version: '3.7'
services:
    backend:
        container_name: backlog-api
        build:
            context: ./backlog-api

        volumes:
            - './backlog-api:/app'
        ports:
            - '5000:5000'
        networks:
            - backlog-network

    frontend:
        container_name: backlog-frontend
        build:
            context: ./backlog-frontend
        volumes:
            - './backlog-frontend:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        networks:
            - backlog-network
        depends_on:
            -   backend

networks:
    backlog-network:
        driver: bridge
